
name: 'pg_dbt'
version: '1.0.0'

profile: 'pg_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  pg_dbt:
    
    +materialized: view
    
    staging:
      +materialized: table
      +tags: ["stag"]
    
    marts:
      +materialized: table
      +tags: ["marts"]
    
    tracking:
      +materialized: table
      +tags: ["track"]

    hub:
      +materialized: table
      +tags: ["hub"]

vars:
  date_range:
    start_date: '2024-01-12'
    end_date: '2024-01-17'

  mart_date_range:
    start_date: '2024-01-12'
    end_date: '2024-01-14'