
pg_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: dbt
      threads: 4

    prod:
      type: postgres
      host: "{{ env_var('PROD_POSTGRES_HOST') }}"
      user: "{{ env_var('PROD_POSTGRES_USER') }}"
      password: "{{ env_var('PROD_POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('PROD_POSTGRES_DB') }}"
      schema: dbt
      threads: 4